version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3006:3006"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
